import BaseHeader from "@/components/BaseHeader"
import '@/app/globals.css'
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerData = [
  {
      name: 'Home',
      href: '/',
  },
]

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={''}>
      <Toaster/>
      <BaseHeader headerData={headerData}/>
        {children}
      </body>
    </html>
  );
}
